# -*- coding: utf-8 -*-
"""chat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMF1NtN9RpQP-Jc0X46DSX02MTCNl5Uq
"""

import streamlit as st
import pandas as pd
from sentence_transformers import SentenceTransformer, util
from transformers import pipeline
import torch

# ==========================
# 1️⃣ تحميل بيانات البنك
# ==========================
bank = pd.read_csv("/content/BankFAQs.csv")
bank["content"] = bank.apply(lambda row: f"Question: {row['Question']}\nAnswer: {row['Answer']}", axis=1)

# ==========================
# 2️⃣ بناء قاعدة المتجهات
# ==========================
embedder = SentenceTransformer("all-MiniLM-L6-v2")
corpus_embeddings = embedder.encode(bank["Question"].tolist(), convert_to_tensor=True, show_progress_bar=True)

# ==========================
# 3️⃣ تحميل موديل Hugging Face
# ==========================
qa_model = pipeline(
    "text2text-generation",
    model="google/flan-t5-base",
    tokenizer="google/flan-t5-base",
    device=0 if torch.cuda.is_available() else -1,
)

# ==========================
# 4️⃣ دالة البحث عن أفضل إجابة
# ==========================
def retrieve_best_context(query, top_k=1):
    query_embedding = embedder.encode(query, convert_to_tensor=True)
    hits = util.semantic_search(query_embedding, corpus_embeddings, top_k=top_k)[0]
    results = [bank.iloc[hit['corpus_id']]['content'] for hit in hits]
    return results[0] if results else ""

# ==========================
# 5️⃣ Streamlit UI
# ==========================
st.title("🤖 Banque Misr Chatbot")
st.write("Ask me anything about banking, loans, accounts, or financial advice.")

user_input = st.text_input("You: ", "")

if user_input:
    context = retrieve_best_context(user_input)
    if context:
        prompt = f"""
You are an expert Finance Chatbot working for a bank. Your role is to assist customers with finance-related questions in a professional, accurate, and easy-to-understand manner.
You must follow these rules:

1️⃣ You are a Finance Expert:
   - You have deep knowledge of banking, loans, accounts, financial advice, risk assessment, and fraud detection.
   - You can analyze customer queries and provide accurate financial guidance based on the context.

2️⃣ You understand the role of a Chatbot:
   - You interact naturally with customers using clear, friendly language.
   - You understand user input through context, previous interactions, and banking terminology.
   - You provide recommendations, guidance, and answers as a helpful assistant.

3️⃣ Instructions for answering:
   - Always use the context provided below to answer.
   - If you don't know the answer, say: "Sorry, I don't know."
   - Provide answers that are concise, clear, and customer-friendly.
   - Avoid unnecessary technical jargon unless required.

Context: {context}
Customer Question: {user_input}
Answer:
"""


        answer = qa_model(prompt, max_new_tokens=200, temperature=0.3)[0]['generated_text']
        st.markdown(f"**Chatbot:** {answer}")
    else:
        st.markdown("**Chatbot:** Sorry, I couldn't find an answer.")


